name: stringsnap 
# Check using `snapcraft register <name>`
base: core18 
# the base snap is the execution environment for this snap
version: '0.1' 
# Version: typically '1.2+git' or '1.3.2'

summary: A short summary which can be 78 characters long
description: |
  Long description of the snap. Preferably under 100 words

grade: stable 
# Options: devel or stable
# devel: development version, not to be published in release channels
# stable: publish in release channels

confinement: strict 
# Options: devmode, strict, classic
# devmode: unrestricted access
# strict: restrict to the environment of snap only. Outside interaction using interfaces
# classic: not available for everyone. Community permissions needed

# icon: gui/icon.png 
# Icon should be present in `gui` folder in the parent directory

slots:
  lib0-1804:
    # Available Interfaces: https://snapcraft.io/docs/supported-interfaces
    interface: content
    content: lib0-1804
    # Content is an arbitary name for the connection. It has to be same on slot and plug side.
    source:
      read:
        - $SNAP/lib

parts:
# parts are used to describe your application, where its various components can be found, its build 
# and run-time requirements, and those of its dependencies.
  stringsnap: 
  # name of the part can be arbitary

    plugin: autotools
    # List of available plugins can be found using `snapcraft  plugins`

    source: code
    # location of source files. Can be a github repository or a folder in the parent directory

    build-packages: [automake, pkg-config, g++, make, libtool]
    # Packages which are used at compile time.

    stage-packages: [] 
    # Packages which are used at run time. Example: gnome-themes-standard
