name: stringrunner 
base: core18
version: '0.1' 
summary: Single-line description
description: |
  This is my-snap's description.
grade: stable 
confinement: strict

apps:
 my-app:
   command: bin/stringrunner
   plugs:
     - lib0-1804
   environment:
       LD_LIBRARY_PATH: $SNAP/extra-libs/lib

plugs:
  lib0-1804:
    interface: content
    content: lib0-1804
    default-provider: stringsnap:lib0-1804
    target: $SNAP/extra-libs

parts:
  stringrunner:
    plugin: autotools
    source: code
    build-packages: [automake, pkg-config, g++, make, git, libtool]
    stage-packages: []
